LPS-169775 The test case versions should keep consistent
petershin/liferay-portal pull request #1870
Opened 2022-12-02 04:31 UTC by Seiphon

2022-12-02 04:31 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-12-02 04:35 UTC, Seiphon commented
tests are passed here https://github.com/Seiphon/liferay-portal/pull/53

2022-12-02 16:37 UTC, petershin requested changes

2022-12-02 16:37 UTC, petershin commented on modules/sdk/project-templates/project-templates/src/test/java/com/liferay/project/templates/BaseProjectTemplatesTestCase.java
> +	public default void setProductVersion(
Please change this to the line below:

```public default String getLiferayWorkspaceProduct(String liferayVersion)```

Then we can do this:

```
String liferayWorkspaceProduct = getLiferayWorkspaceProduct(liferayVersion);

if (liferayWorkspaceProduct != null) {
    writeGradlePropertiesInWorkspace(workspaceDir, "liferay.workspace.product=" + liferayWorkspaceProduct);
}
```

2022-12-05 07:52 UTC, closed without merging

2022-12-05 07:54 UTC, Seiphon commented
resend here https://github.com/petershin/liferay-portal/pull/1871